version: '3.8'

services:
  connectify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - /etc/vibecast/ssl:/etc/vibecast/ssl:ro
      - /etc/vibecast/wwwroot/avatars/:/etc/vibecast/wwwroot/avatars/
    environment:
      - ASPNETCORE_URLS=https://+:${HTTPS_PORT};http://+:${HTTP_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/vibecast/ssl/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/vibecast/ssl/privkey.pem
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=${MYSQL_PORT};Database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_PASSWORD};
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Key=${JWT_KEY}
  mysql:
    image: mysql:8.0
    container_name: connectify-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: