version: '3.8'

services:
  connectify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /etc/vibecast/ssl:/etc/vibecast/ssl:ro
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/vibecast/ssl/fullchain.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/vibecast/ssl/privkey.pem
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=connectify;Uid=root;Pwd=;

  mysql:
    image: mysql:8.0
    container_name: connectify-mysql
    restart: always
    environment:
      MYSQL_DATABASE: connectify
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: connectifyuser
      MYSQL_PASSWORD: connectifypass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: