version: '3.8'

services:
  connectify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - /etc/vibecast/ssl:/etc/vibecast/ssl:ro
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/vibecast/ssl/yourcert.pem
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/etc/vibecast/ssl/yourkey.pem