services:
  db:
    image: mysql:8.0
    container_name: connectify-mysql-debug
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connectify
      MYSQL_USER: connectify_user
      MYSQL_PASSWORD: connectify_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data_debug:/var/lib/mysql

  connectify:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: connectify-debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=connectify;Uid=connectify_user;Pwd=connectify_pass;
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000", "--no-launch-profile"]

volumes:
  db_data_debug: